### PR TITLE
added csv support

### PR DESCRIPTION
**Pull request by csells**

### CODE REVIEW

**Comment by timsneath** [comment]
This looks good. I need to do a little lightweight refactoring on my side, since I've added another command here.

**Comment by timsneath** [comment]
I've merged these changes in manually, since the refactoring work I'd done made it very challenging to resolve the conflicts. Please take a look and see if I missed anything.

@kf6gpe -- please note that I _didn't_ include your cron script, since I figure that should stay in your fork. Hope that's OK.

**Comment by kf6gpe** [comment]
Looks good to me, I think. @csells, are we missing anything?

I agree, you probably don't want cron.sh. I just wanted to stash it somewhere where we don't lose it. It's not terribly portable anyway.

**Comment by csells** [comment]
lgtm

**Comment by timsneath** [comment]
Closed with thanks!

**Pull request closed without merging**
